// Generated by goasset(1.0 20200425) or "go generate" . DO NOT EDIT.
// https://github.com/hidu/goasset/

package handler

import (
	"reflect"
	"sort"
	"testing"
)

func TestAsset(t *testing.T) {
	got := Asset.GetFileNames("/")
	sort.Slice(got, func(i, j int) bool {
		return got[i] < got[j]
	})
	want := []string{

		"/asset/css/style.css",

		"/asset/favicon.png",

		"/asset/html/index.html",
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("Asset.GetFileNames(\"/\")=\n%v, want=\n%v", got, want)
	}
}
