// Generated by goasset(1.0 20200425) or "go generate" . DO NOT EDIT.
// https://github.com/hidu/goasset/

package handler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"mime"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"time"
)

// AssetFile one asset file
type AssetFile interface {
	Name() string
	ModTime() time.Time
	Content() []byte
	ContentGzip() []byte
}

// assetFile asset file  struct
type assetFile struct {
	name        string
	mtime       time.Time
	content     []byte
	contentGzip []byte
}

func (af *assetFile) Name() string {
	return af.name
}
func (af *assetFile) ModTime() time.Time {
	return af.mtime
}

func (af *assetFile) Content() []byte {
	return af.content
}
func (af *assetFile) ContentGzip() []byte {
	return af.contentGzip
}

var _ AssetFile = &assetFile{}

// AssetFiles asset files
type AssetFiles interface {
	GetAssetFile(name string) (AssetFile, error)
	GetContent(name string) []byte
	GetFileNames(dir string) []string

	FileHandlerFunc(name string) http.HandlerFunc
	HTTPHandler(baseDir string) http.Handler
}

// assetFiles asset files
type assetFiles struct {
	Files map[string]*assetFile
}

var _assetDirect bool

var _assetCwd, _ = os.Getwd()

// GetAssetFile get file by name
func (afs *assetFiles) GetAssetFile(name string) (AssetFile, error) {
	name = filepath.ToSlash(name)
	if name != "" && name[0] != '/' {
		name = "/" + name
	}
	if _assetDirect {
		assetFilePath := filepath.Join(_assetCwd, name)
		f, err := os.Open(assetFilePath)
		log.Println("[goasset] Asset Direct, name=", name, "assetPath=", assetFilePath, "err=", err)

		if err != nil {
			return nil, err
		}
		defer f.Close()
		info, err := f.Stat()
		if err != nil {
			return nil, err
		}
		if info.Mode().IsRegular() {
			content, err := ioutil.ReadAll(f)
			if err != nil {
				return nil, err
			}

			helper := newAssetHelper()
			contentNew, errHelper := helper.Execute(assetFilePath, content, "")
			if errHelper != nil {
				return nil, errHelper
			}
			return &assetFile{
				content: contentNew,
				name:    name,
				mtime:   info.ModTime(),
			}, nil
		}
		return nil, fmt.Errorf("not file")
	}
	if sf, has := afs.Files[name]; has {
		return sf, nil
	}
	return nil, fmt.Errorf("not exists")
}

// GetContent get content by name
func (afs *assetFiles) GetContent(name string) []byte {
	s, err := afs.GetAssetFile(name)
	if err != nil {
		return []byte("")
	}
	return s.Content()
}

// GetFileNames get all file names
func (afs *assetFiles) GetFileNames(dir string) []string {
	if dir == "" {
		dir = "/"
	}
	names := make([]string, 0, len(afs.Files))
	dirRaw := dir
	dir = path.Clean(dir)

	if dir != "/" && strings.HasSuffix(dirRaw, "/") {
		dir += string(filepath.Separator)
	}

	dir = filepath.ToSlash(dir)

	for name := range afs.Files {
		if strings.HasPrefix(name, dir) {
			names = append(names, name)
		}
	}
	return names
}

// FileHandlerFunc handler http files
// 若目录名称 为 *private 则不允许通过web访问
func (afs *assetFiles) FileHandlerFunc(name string) http.HandlerFunc {
	if strings.Contains(name, "private/") {
		return http.NotFound
	}
	return afs.FileHandlerFuncAll(name)
}

// FileHandlerFuncAll handler http files
// 无 private 目录规则
func (afs *assetFiles) FileHandlerFuncAll(name string) http.HandlerFunc {
	name = filepath.ToSlash(name)
	file, err := afs.GetAssetFile(name)
	return func(writer http.ResponseWriter, req *http.Request) {
		if err != nil {
			http.NotFound(writer, req)
			return
		}
		modifiedSince := req.Header.Get("If-Modified-Since")
		if modifiedSince != "" {
			t, err := time.Parse(http.TimeFormat, modifiedSince)
			if err == nil && file.ModTime().Before(t) {
				writer.Header().Del("Content-Type")
				writer.Header().Del("Content-Length")
				writer.Header().Set("Last-Modified", file.ModTime().UTC().Format(http.TimeFormat))
				writer.WriteHeader(http.StatusNotModified)
				return
			}
		}

		mimeType := mime.TypeByExtension(filepath.Ext(file.Name()))
		if mimeType != "" {
			writer.Header().Set("Content-Type", mimeType)
		}
		writer.Header().Set("Last-Modified", file.ModTime().UTC().Format(http.TimeFormat))

		gzipContent := file.ContentGzip()
		var errWrote error
		if len(gzipContent) > 0 && strings.Contains(req.Header.Get("Accept-Encoding"), "gzip") {
			writer.Header().Set("Content-Encoding", "gzip")
			_, errWrote = writer.Write(gzipContent)
		} else {
			_, errWrote = writer.Write(file.Content())
		}

		if errWrote != nil {
			log.Printf("[wf] wrote %q with error:%s\n", name, errWrote)
		}
	}
}

// HTTPHandler handler http request
// eg:on file system is :/res/js/a.js and request is /res/js/a.js
// http.Handle("/res/",res.Asset.HttpHandler("/"))

// eg:on file system is :/res/js/a.js and request is /js/a.js
// http.Handle("/js/",res.Asset.HttpHandler("/res/"))
func (afs *assetFiles) HTTPHandler(baseDir string) http.Handler {
	return &_assetFileServer{sf: afs, pdir: baseDir}
}

type _assetFileServer struct {
	sf   *assetFiles
	pdir string
}

// ServeHTTP ServeHTTP
func (f *_assetFileServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	name := filepath.ToSlash(filepath.Join(f.pdir, r.URL.Path))
	f.sf.FileHandlerFunc(name).ServeHTTP(w, r)
}

var _ AssetFiles = &assetFiles{}

var _ = flag.String
var _ = runtime.Version()

// ---------------------------helper.go--------begin--------------------------//

func newAssetHelper() *assetHelper {
	helper := &assetHelper{}

	helper.Regs = make(map[string]*regexp.Regexp)
	helper.Regs["remove_above"] = regexp.MustCompile(`[\S\s]*?//\s*asset_remove_above\(\s*\)`)
	helper.Regs["remove"] = regexp.MustCompile(`//\s*asset_remove_start\(\s*\)[\S\s]*?//\s*asset_remove_end\(\s*\)`)
	helper.Regs["include"] = regexp.MustCompile(`//\s*asset_include\(([^)]+?)\)`)

	helper.RegisterFn("remove_above", helper.RemoveAbove)
	helper.RegisterFn("include", helper.Include)
	helper.RegisterFn("remove", helper.Remove)

	return helper
}

type assetHelperFn func(fileName string, content []byte) ([]byte, error)

type assetHelper struct {
	Fns  []map[string]assetHelperFn
	Regs map[string]*regexp.Regexp
}

// RegisterFn 注册helper方法
func (h *assetHelper) RegisterFn(name string, fn assetHelperFn) {
	h.Fns = append(h.Fns, map[string]assetHelperFn{name: fn})
}

// Execute 执行所有的helper方法
func (h *assetHelper) Execute(fileAbsPath string, content []byte, skipFnName string) (contentNew []byte, err error) {
	contentNew = make([]byte, len(content))
	copy(contentNew, content)

	for _, fnInfo := range h.Fns {
		for name, fn := range fnInfo {
			if name == skipFnName {
				continue
			}
			contentNew, err = fn(fileAbsPath, contentNew)
			if err != nil {
				return nil, fmt.Errorf("%s,current file is: %s", err.Error(), fileAbsPath)
			}
		}
	}

	return contentNew, nil
}

// RemoveAbove 删除在此标记之前的内容
// eg: \/\/ asset_remove_above()
func (h *assetHelper) RemoveAbove(fileAbsPath string, content []byte) (contentNew []byte, err error) {
	contentNew = h.Regs["remove_above"].ReplaceAll(content, []byte(""))
	return contentNew, nil
}

// Remove remove 方法, 删除指定区间里的内容
// eg: \/\/asset_remove_start() 中间的内容被删除 \/\/ asset_remove_end()
func (h *assetHelper) Remove(fileAbsPath string, content []byte) (contentNew []byte, err error) {
	contentNew = h.Regs["remove"].ReplaceAll(content, []byte(""))
	return contentNew, nil
}

func (h *assetHelper) include(fileAPath string, content []byte, includeFiles map[string]map[string]bool) (contentNew []byte, err error) {

	fileAPath = filepath.Clean(fileAPath)
	includeFiles[fileAPath] = make(map[string]bool)

	contentNew = h.Regs["include"].ReplaceAllFunc(content, func(matchData []byte) []byte {
		idx := bytes.Index(matchData, []byte("("))
		name := bytes.TrimSpace(matchData[idx+1 : len(matchData)-1])
		if len(name) == 0 {
			err = fmt.Errorf("asset_include with empty param")
			return []byte(err.Error())
		}
		fileBPath := filepath.Join(filepath.Dir(fileAPath), string(name))

		if bFiles, hasB := includeFiles[fileBPath]; hasB {
			if _, hasA := bFiles[fileAPath]; hasA {
				err = fmt.Errorf("asset_include error: cyclic include,%s include(%s)", fileAPath, string(name))
				return []byte(err.Error())
			}
		}
		includeFiles[fileAPath][fileBPath] = true

		includeFiles[fileBPath] = make(map[string]bool)

		bContent, errRead := ioutil.ReadFile(fileBPath)
		if errRead != nil {
			err = errRead
			return []byte(err.Error())
		}

		b1Content, errB1 := h.Execute(fileBPath, bContent, "include")
		if errB1 != nil {
			err = errB1
			return []byte(err.Error())
		}

		cContent, errInclude := h.include(fileBPath, b1Content, includeFiles)
		if errInclude != nil {
			err = errInclude
			return []byte(err.Error())
		}
		return cContent
	})

	if err != nil {
		return nil, err
	}
	return contentNew, nil
}

// Include 将另外一个资源文件包含到当前文件里
// eg: \/\/ asset_include(a.tpl)
func (h *assetHelper) Include(fileAPath string, content []byte) (contentNew []byte, err error) {
	// 用于检查循环include
	includeFiles := make(map[string]map[string]bool)
	return h.include(fileAPath, content, includeFiles)
}

// ---------------------------helper.go--------finish-------------------------//

// Asset export assets
var Asset AssetFiles

func init() {

	// nolint
	var _assetGzipDecode = func(data []byte, fileName string) []byte {
		gzipReader, errGzip := gzip.NewReader(bytes.NewBuffer(data))
		if errGzip != nil {
			panic(fmt.Sprintf("[goasset] gzip decode failed,file=%q, err=%s", fileName, errGzip.Error()))
		}
		defer gzipReader.Close()
		buf, errReader := ioutil.ReadAll(gzipReader)
		if errReader != nil {
			panic(fmt.Sprintf("[goasset] read decode content failed, file=%q err=%s", fileName, errReader.Error()))
		}
		return buf
	}

	// nolint
	var _assetBase64Decode = func(txt string, fileName string) []byte {
		txt = strings.ReplaceAll(txt, "\n", "")
		bf, err := base64.StdEncoding.DecodeString(txt)
		if err != nil {
			panic(fmt.Sprintf("[goasset](%s) base64 decode failed, err=%s", fileName, err.Error()))
		}
		return bf
	}

	asset := &assetFiles{Files: map[string]*assetFile{}}
	Asset = asset

	{
		// 0 mtime: 2020-12-27 08:59:27 , size: 6180
		fileName := "/asset/css/style.css"
		contentBase64 := `
H4sIAAAAAAAA/6xYUY/buBH+KzoEB+QCUZHt9TpLoUH71gIt0Ie+HYKCEkcWG4okSGrtjc7/vSApyZQl7+4dDkGwq+HMcMhv5pvhfv70k5C6JZz9gKwyJnne
ZXm2TX5L/vWP/yT/ZBUIA8lvyZHZjMnPk+6nz41teV9LYZFhPwBvcnUu/GdNWsZfsCHCIAOa1QU6QfmdWWSJQg07NpwdG4sqyaXGVhNhFNEg7FUPzsErIvR/
nbF4k+c/F6g16yuXUtKXviX6yATOZ0E0wJ/BsookAjpI/z5+pn/TjPA0ijE6yYM6F5wJQA24QPEme9h+2R82D7sixPxht9sVJam+H7XsBB1O8qGu60IRSpk4
IisV3ufqfPmUYlJb0CkuoZYa+vGQpTy7/Zg44lJqCtpJCtTKH3eWVqUX0i8CYYJZRviFYFJZ9gwpwY18Bt3Lzrpz4fzSbMb7yh4P0CZ5dP4ttJeys1aKlAnV
2VQq6/yr1ACHyqYOBKKBzK8cM9GAZrYYg/Bfg6fe7V9zecLPzLCSw7hDcNl7XH0q1FK3WEgxabg8S3wgv9oXBX8J4m9pJNJgwM4kpitbZr9Nl02UAqKJqAAH
+6LqtJEaK8mEBT1s9itlhpQc6Ld420nYD0YUatLx8WwYe9BqWXUGMSFAh0iW8n7IDpwXAUGcX7xqH6dbqLFLdBrRtSXobxiPx/HekFFMoBipO9qys3PtftiJ
dFbG+xggumq+raVoJYUFYVdzNF67Z7LEwUFeM+B0JYJr7EGAKmfCVw57z4BCJTWxTIq1HPD5Rfqpmg+kPBQ+B692gxL2+E0lNJhsd/vtoVqYdIKCdliOdlPJ
UWkt0MQ2TBSjbAwsZIh2tOHdJw6XZK/OoyaSdW3AYrRV54uayi7JE8e6rphjzhvr0MtOAel9nt9Q2uamTjNXeMhhpiXvKTOKkxdccll9L06M2iaQ8GC/cxw5
ZvOjOieb7Uj/7+XQ/X5/h0MjKWvJMcA1VsxGnRMjOaPJh6qqBinShLLOYLfrLHkbQuUJM2HAuttygapzoo8l+Zin7l+WH/a/FL9Hd2pSjq2Yh30IIoAHxABi
wlVdkm32Jl0GtNApkHy/v9f8/BlO5qkw5HHsDX94fCQ1PE2JnP+RS09d/n4ZFzb5Nt0c9ul2t0uzx9+FyKuObg4TKFlxUkEjOb0W9NPTUyEVqZh9wZsbIzd4
eMq5Y7jYY2Lp12xKK6YyY8LXSqi2RVmFekeltFa2OL8ts7jOHxZ1PpWd5yrC2VHgClzPK04Ns4CMIp4RT5qo4hm0G4/4oNgySjmEyUt2VYPcQCEFbolgquOe
9Ir7K/MeOyVJZ1w78o0/lLYHZUVqlsKF4J1kEY2Z/urR0MP7Nye6eeZXVXXJArB+JuqVHOpNgzv1MxQjqNYNDZE5J8oANqCIJhZmXpI5+y59/kBMUDjjbVFz
SSzmUNuYlm9SZOYcuUxburxmUb6SCa+El86cE0qlSBf7zS4BVcD5em4tIsWcGIuqhnH61QG1cH2rMOAw3IC7GIw26rxw7JWX93DJBHkuiUbuiMkM2pvqDHje
OYW7G8KiGQ/pUID7a6MMwXnJEK2exrAijt/PZX9tgTLysWUCBaAPj1/U+Zc+2mqQ+3fGUv/pabuq/3RY199s83zVYLMJFhmhFDmwCQdt06wk9AhpAIlqqag8
CdSC6NKMtUekJCdaMppmnJTA06yVlPDU3be7S/OVs6/Ef37NwkNl+HRohDk6U1K5sSvNlJZHDcakWcioUFZA08xKyS1T0y+j6Qk4Hx4wSsPi7XIdYkOXcbTx
E2uV1JZET9H7GtFKnuSrpvFoMtMIe99bfnNlIpPxl1hljQ+v62O6rxCCy4RmHBcXbWfrRK/R6vtGsbGJb4effoi7xWJV6Y31WR1PDy03HydRxWE3JyAvGMJ1
D/VXzzOcf13njbknDzPJdr9Px//Zxg0s9xfvTT5/wNUlawkT/bLxX3veJbPMcpi9H/5NKlazSqaufXuGdG4SNb/UfBDPGDPaKupQj1ODCsy2NEwW/WO0dES+
oh6q+b9wVkzDyGv7t5TtRGi5Osc18dYOyfBnitv3e6Br/1D0regFOJen9ZnCTxOx2vCinGs8XrIGiLbxX9ayB2gHzDRQN21KC1EFk9JI3lk3awwTYoSDbzFF
DF00NwxNIJGCvySm0gAiIYImH1tyHrrCw5fQFJZgj7f+8/sRehPOewhd/g8AAP//AQAA//+wO//fqBQAAA==`

		contentGz := _assetBase64Decode(contentBase64, fileName)
		oneFile := &assetFile{
			name:        fileName,
			mtime:       time.Unix(1609030767, 0),
			content:     _assetGzipDecode(contentGz, fileName),
			contentGzip: contentGz,
		}
		asset.Files[fileName] = oneFile
	}

	{
		// 1 mtime: 2017-05-20 21:04:49 , size: 3228
		fileName := "/asset/favicon.png"
		contentBase64 := `
H4sIAAAAAAAA/wCcDGPziVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAMY0lEQVR4nOVbe1iUVRp/z3ebOwyC3Bpuw3CRLTMyJUtFMiLiAR/W
dFMza10ttwtrVm7b41Om5lq5PuXaZmRktrVkpkRGrpprZEZJaoRchjsiAcLI3L755ptz9o+CBAYZhm+k5+n3F3znPb/zO+985/Ke836IEILgNwxqvAWMN5jx
arhh+iKd41x9PuYdKYimecQyJaxe91Ls6b0VV1MHGo8h0Hjb8mB7aflxIjjjB6pBAh3g94o6c+a6a955gb8aWsbFAVX+NxfgXsvS4cqRQnZSfn3Cgpiv3m31
tZZxmQOIKKZfsdzuSLGfqjxuTMhK8rWWcXEAYuhvRzRyitFC/fmjxmvnTfGpFl8Ngc71r2lNbx2IxHY+nJJxHOYdAmDSrclObce8A5v3H91NbHzqiEQM08XF
6tIMVR/7ZHKU3AG1MRlZrq6etdhqnwaEuF9laIpHHGcidj7UI1KGaZVNipkVe3Zfo4RSAUBiB9RE3r5MbGnPBx8MLSTnKhUpU2ZFf/5mt5S8kgp19fSukZqz
D4QXkuxlZ//duW47JyWvtGIx1krKNwjExqdf3P7eFik5JXUAoqhjUvK5A+7pfbgm8vYlUvFJ6gDud7FrkVxWOXxrkkw3lNjWub027q4sKcgkXwU6nnmVM+0u
Ssdm6xQgoAYg3ZRa1chGhvLOprZXxLbOSImawpRW8778+oS86GNvdXlL4vOtcOvCNUrL4a/WYZM5DzCRdAIDAACWaWUjw5bFGQ8e9aa6Tx1Qq89IES907iK8
kOirNn6GSE8M2BTy4uMbtPfliKOp6BMHWD77kjq/9OnVrs6eDUB88KsPA6RSFCumT14afSTf5HEdqR3QdMdKtf2rM7ux2TpPSl5PgeRcBRcfnR175sNGj+yl
dED9tHt0ju9riggv+DSAGREs0yqLj8qMrdg/YvwgmQOMCVl6Z2NbCRGcBin4xgya7ub0unRDTXH5lcwkcUCtIdPgbGo7DqLLs+DmaoGmu2WJMWmxFR+dHc5k
zBuh+qkLI8WW9pJfXecBAFyuCY6axuK6ybnRw5mMyQFNty33c/xgLCKCUz8WHp/CKeqE2uaixlvu9XNX7LUD7N/+QNm/qSggvDDZe3VXB4R3XMtXGHe6K/Pa
Ac2Zq1aN11LnDXCvZUFN2JwHBz+/ogO6XsjnqifOfKZh5tKgy5/XJd8d7+o2bZJapK8hdnZvqb/pDwOG67AXI/VTF+odlXW7id0xQ6isZwDg2b4yoaZpB7iw
2ndSfQQXVgtVDdsAILvvkds3oHHmffH8meoyYnfMAABwma2rWnLztAAANVHpucRqT5NKE+WvLmD1unSkVIx8UiwBsMWWWWvITO1vv++Puinz08wfH6MAAKK/
eLuG0qj29NdyikG2L8pX9H74X8bV2b1OMjUUErjYiE1xdZ8ejjq4I4WNDFuA5Nzw5wkSterq6H66/x8AgKY7VuocZ6pLWhc+UVarvzMDACDslb+uofzVhX2G
rkvmvI5nXp1P7A7JZn1Ko96tP1VoBABQzp6K45oO7Q3e+FgyHRK4AjhWklshpFKUsXpdJhMalNf3DJutaY2zlxkAfnYAX34uFwAYYueTnQ2txVWa6Yc7N70x
VTVn2jKkkP0UZzvFUKG2KV8KUQAAQCFBlhizefDjwNVLhYT2Y/na++cl0hMDngSW8eqwA6kU5axelx3zv4IZcXWflsinX1dwGRflqKybB/DzVrhKM70UW2wz
BnFgSqMqkiXpt/Knq3cQh3CtN0KGA6XV5Cf2nFgxkl1z5kNa+9ffP+m6ZH4UXFg5kj1SysuZ4MD1uve3FCumT8aXl1VNuGUz7ul9EgAAqRX7J5nLcqmGW+6N
xhZbijuN2GydZy+rOEwICfa4Z56AQoIsKdajZTTy4GumhIulTytn3phIaTU7ASHBnR2Sy86yUeG5EYUvT4trKCka3HkAAMUNk7YDRf1060xgCgAAshz9mv5x
7bZ4Z2NbKrHZ04gophJeCBpcWVIgJFIaZSEdHFgQ+vKao5rsOUPEDof6GxfEC8aWDbjXkgsAFFLIKuhA7YaQzX/Z57/4rhFPg6q0NxfgS5alQCEh5B9PTRgS
DVoOn2Q6ntqa5Gxpn0vsjlTsEGaBU3S7j5YCSMYZKY1yN5cQvSum9J02T+sZk3KmYZNZH/Lymr3+92R6fAxWn7wgmf/u3LcAANo/5kYPGw6fX/r0BMuhE/Ow
ybyaOASfX1MDTdkohbyQ1et2xp758KTU9E23/ymUP1uTTWz8AmyxpQEA+N+TaRjiAOOk7EixrWMbttrTPZl0fACMlPIKSqMqUM2eukf3n5e8PvJuz/u7+tL7
n6YTu2MJttgyAGP55eX+S7L0Qxxw4c8b/XpeL2zr7zzLNNJazWFXZ89yb4V4AiRju4nDOWHAQ5qyUUrFfjpIuztgxfxjQWuXu50AL8fPnc4kdn4+tvIZiKF7
iUMIBTe73qC/rQh3OwSq/FIKsdk6HynkJ+RTEhY4G89niRe6/jWWDl4RDN2rzrjVwJ+qzBa7ejaBUxyy6iCO7UAK2V4uNqJAf6pwwLa5ddFTwdajX6cTOz8P
2/h0EF1qQEikA/y2qeamPGsp+XIn7rUsGsRnmuQon+A2GEJKeSFFIZv6zpkP6t7bwleHzfFpJgli6LLIj7d3AcCupjtWFtnLvt+MTeZlcNmvRgRnMBGcq/jy
c6vOqaeVU2rlHiCEITZ+Prbap1x+/I7kXCUTEbo8ruaTkwAANRFzD7lxQCPAMNFg4MP3FKnvmrVPfsMkDACAEHi8THkH1M8f9dnrXQCw3JiQVeBsad/ubutN
rPZkl9WePJQGiXSg/1ZNTtr68PznbL9UcJOogVAlwDDRYNAzK4W+zgMAAMv6NGWNiK6UxtuWDxj/huri0sC8e6chtWKfpzxM+MR1CZ1frB3QeQDAZlvuYFvE
MeUAHp4IIQDfpquJoh//TcWu84vXDpilez86kkh4YZbHND925xmTcvrtuzbt5KqDZ63HvZaMwbZ0cGApgIfH4q0LHtf1fnCo2VMh3gLJuBqkkBUihDqIC0/G
VtuiwUsx4tg2pJDvR3KugtgdEwAgFfda0uCXHxMjpbyKOEUToigDcQhDJ1QZ2xX+5vPh/ovvEj1ygP2rM1Rj2gNthB9KdtVAUzZ6gv967X0520NefHzAK15/
w91TBGPzFmyxzfWEitKoChJ7Tz4A4OEQUNx8PUYMUzp61dIAyblKWWJMSkLH8S2DOw8AoP/ug9NRh9/IYMImPtwf7FwBdFDA+31/e7y8IZWi2HPJ0gHJZSdU
adNnjXTPp5g+Gce3Hd3BGSIygKGHzSRDMrY+5IXH+nMJPHaA8tbk/cDQFk/tpQCSy04oUiZnRn6yw+PUOEN18XEuNjIVGMZtYEX5a3b4LczoD548dkDE3q0m
Sq3c7an9WIHkstPK1Juyoj/f1Tvauoaqogo2KmwusEz7gAKWaddkzhxwQTKqHZ5skn4L0NSQMSg5WKaDi4+aH/Xpax4nOgxGnPFglSwuKhsYut+BdIDflvC3
Ngx4i0flgJgTe5ppf80Gb0V5CvaakLzYMx/Wj5Un9of937K6kCUAICK5rEJ7X86OwTajvh7v2riT69y48zCxO24dq8Bh8VMUWEr5qfbEtx7ZM3KFK6MmbM6z
SK0siav9ZMg5g1f5AQ0zloTzpyqP+TwZAoHIxkakxdUe9NkS7FWUF3NiTxsbG5GOONYotaABIMCIze27mnMe8VkKrtdhrqHyQKPsuri5SCG7YgrKWEEEp8F6
5Os97Y9sko9sPXqMOUWmdf5qpfXzss2u7kurwIdfoFBqZbFy9tRlkcX/dLsnMCblTBVb2vMBoSpKrSiWXRe/P+qz10fct4xZsG7vVlvCxdJHubioVKSU++xt
wBZbluXQidM14XNWtK14LhgAwPTWR2pjUk5KVcCMHUJ1w3FssU3GFlsuEUSDJmu2RyG8pGlyloNfUBceen6eeNG0hljt08CX3yQhsAEB+eVtIJXiJBsenGeo
KS7zmMZXqbL1UxcmC8aWRcQh5BLeEe2LNgAAgKZ4SqU4RAf477zm3c0lyltuGNXp1VX5brAhZXGSUNecSgTxVsA4GVvt0V6m0GKkUrQhhM4CQ5fTgdpSTdbs
k6Hbnhr1drkP4/LhpKnggNz09oFIoa7FgCgUjM1WNXY4GSCDxMlYkfZTWQiBbjZsotHv93NbA5+43+vOusO4OODXhN/81+P/B/RuMv7CTja0AAAAAElFTkSu
QmCCAAAA//8BAAD//wfkti2cDAAA`

		contentGz := _assetBase64Decode(contentBase64, fileName)
		oneFile := &assetFile{
			name:        fileName,
			mtime:       time.Unix(1495285489, 0),
			content:     _assetGzipDecode(contentGz, fileName),
			contentGzip: contentGz,
		}
		asset.Files[fileName] = oneFile
	}

	{
		// 2 mtime: 2020-12-31 22:19:32 , size: 2071
		fileName := "/asset/html/index.html"
		contentBase64 := `
H4sIAAAAAAAA/5RWwXLbNhA9U1+B4FBdQkNSUtt1AXY6ig/pdNyM08y0Jw9ErkQ0IIACS0pqJv/eAUHZciOX9knA7nsPi8Wbpfird78tf//zwzWpsdHFhMcf
oqXZCAqGxgDIqpjwBlCSspY+AAra4jq/pIdwjehy+LtVnaB/5J9+zpe2cRLVSgMlpTUIBgV9fy2g2sBJ1lKWNeRLa9BbfcRp5C6XGxCL739YzGYzStiBbWQD
gnYKts56PKJsVYW1qKBTJeT95jVRRqGSOg+l1CDmsQRUqKH4vMudt7s9Z2k/4VqZz6T2sBaUyRAAWRkCC7jXcFaG8FO3oMSDFrQPhRoA6YHWx1VpDSW4dyCo
auQGmDMb+lhyLbsIO4uZeCOWmjzhK1vti0nGK9WRUssQBI0Xk8qAJ41U8UWyjNfzQ7Yvmx7do573iCMBI7uV9D0x42vrm8eJPIYokSUqawRllDSAta0EdTZg
oj3SU8a1mG+8bd2QzXgfGy6NsIvvkcBRPC8P75oerfWaJl7mtCyhtroCL2g0xBVjsJONi922DaOkk7oFQb98ObuV269faUGGI4OT5kRJ+QoNCaChxDvYOeXh
npLxFE9lTFN2eqpScrhYlnHrYmOGOqazaXHd88gVubGcpexT6PPZtJiTRpkWYRwbwbMBHcbg88uIf3OPf+286uT4MW/SOaS2rR/DXiwidtFjRwu6PH+blCu5
Hy3+YnGZpCu5H1U+n73t0RfPQg+jou/NKTxnyQUH67JopOKlpnrY4b1X/msvfMJbhAT1Dwg6p6RpNSqnQdDD6knnReMhmKCsuRp3nrF3/fAJ0+LGkvf98hmc
vxL+l4/PwJYhgZdhVNl5uDOxIcUHD9rKSpkNuYEdfkt8lef/IxKqRxIfZQPknRo1svNwzPsGnudPMb3c3rVeT4tbuSWfbn99iZuycVM9eGfVIlozjNDQrhr1
MESj+1Zo8grWstXYr/egtd3SYmPJd156/yNnSeJEJZxVqkvzn0Ur9l+IITb8cpY+PZz1/wP+BQAA//8BAAD//xFCZEYXCAAA`

		contentGz := _assetBase64Decode(contentBase64, fileName)
		oneFile := &assetFile{
			name:        fileName,
			mtime:       time.Unix(1609424372, 0),
			content:     _assetGzipDecode(contentGz, fileName),
			contentGzip: contentGz,
		}
		asset.Files[fileName] = oneFile
	}

}
